version: "3.8"
services:
  app:
    build: .
    ports:
      - "80:8080"
    depends_on:
      - db
  db:
    container_name: dbhost
    image: postgres:alpine
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: wallet
    ports:
      - "5432:5432"
    volumes:
      - ./schema:/docker-entrypoint-initdb.d
  